apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  labels:
    app: nexus
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp/optimal/nexus
    server: 10.211.55.4
