apiVersion: v1
kind: Service
metadata:
  name: nexus-client-service
  namespace: devops-tools
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /
    prometheus.io/port:   '8081'
spec:
  selector:
    app: nexus-server
  type: NodePort
  ports:
    - port: 8132
      targetPort: 8132
      nodePort: 32132